package View;

import Controller.UIController;
import Controller.command.Command;
import Controller.command.LoginCommand;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginPage implements ActionListener, Page {

    private JPasswordField passwordField1;
    private JTextField nameField;
    private JButton logInButton;
    private JPanel mainPanel;
    private JButton signUpButton;


    public LoginPage() {
        logInButton.addActionListener(this);
        signUpButton.addActionListener(this);

    }

    @Override
    public void onStart() {
        UIController.getUIController().setCurrentUser(null);
        nameField.setText("");
        passwordField1.setText("");
    }

    @Override
    public JPanel getPanel() {
        return mainPanel;
    }

    @Override
    public boolean isMenuVisible() {
        return false;
    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Nickname:");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        mainPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Password:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label2, gbc);
        passwordField1 = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(passwordField1, gbc);
        nameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(nameField, gbc);
        signUpButton = new JButton();
        signUpButton.setText("Sign Up");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(signUpButton, gbc);
        logInButton = new JButton();
        logInButton.setText("LogIn");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(logInButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton pressedButton) {
            switch (pressedButton.getText()) {
                case "LogIn":
                    System.out.println("Log in pressed");
                    char[] password = passwordField1.getPassword();
                    String nickname = nameField.getText();
                    Command c = new LoginCommand(nickname, password);
                    c.execute();
                    break;
                case "Sign Up":
                    UIController.getUIController().setCurrentPage(Pages.SignUp);
                    break;
            }
        }
    }




}