package View;

import Controller.UIController;
import Controller.command.Command;
import Controller.command.WarningCommand;
import Model.db.UserDatabase;
import Model.nodes.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class SearchUserPage implements Page, ActionListener {


    private JPanel mainPanel;
    private JPanel northPanel;
    private JPanel listPanel;
    private JList<String> foundList;
    private JTextField textField1;
    private JButton searchButton;

    DefaultListModel<String> listModel;

    public SearchUserPage() {

        searchButton.addActionListener(this);
    }

    @Override
    public JPanel getPanel() {
        return mainPanel;
    }

    @Override
    public void onStart() {
        Page.super.onStart();
    }

    @Override
    public void onExit() {
        textField1.setText("");
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == searchButton) {
            for (User user : UserDatabase.getInstance().getKeys()) {
                if (user.getNickname().equals(textField1.getText())) {
                    int option = JOptionPane.showConfirmDialog(
                            UIController.getUIController(),
                            "Profile Found want to go ? "
                    );
                    User u = UserDatabase.getInstance().searchByNickname(user.getNickname());
                    if (option == JOptionPane.OK_OPTION) {
                        UIController.getUIController().showProfileFor(u);
                    }
                    return;
                }
            }
            Command wCommand = new WarningCommand("Profile with given nickname not found!!");
            wCommand.execute();


        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        northPanel = new JPanel();
        northPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(northPanel, BorderLayout.NORTH);
        textField1 = new JTextField();
        northPanel.add(textField1, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setText("Search:");
        northPanel.add(label1, BorderLayout.WEST);
        searchButton = new JButton();
        searchButton.setText("search");
        northPanel.add(searchButton, BorderLayout.EAST);
        listPanel = new JPanel();
        listPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(listPanel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
