package View;

import Controller.UIController;
import Controller.command.ChoosePhotoCommand;
import Controller.command.Command;
import Controller.command.SignUpCommand;
import Image.*;
import Model.nodes.User;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.RenderedImage;
import java.util.Objects;

public class SignUpPage implements ActionListener, Page {
    private JTextField nicknameTextField;
    private JLabel passwordLabel;
    private JLabel nicknameLabel;
    private JPasswordField passwordField;
    private JTextField nameField;
    private JTextField surnameField;
    private JButton SignUpButton;
    private JPanel mainPanel;
    private JButton profilePicButton;
    private JLabel photoLabel;
    private JRadioButton freeTierRadioButton;
    private JRadioButton hobbyTierRadioButton;
    private JRadioButton proTierRadioButton;
    private JRadioButton adminRadioButton;
    private JButton toLoginButton;

    private ButtonGroup tierButtons;

    public SignUpPage() {
        super();
        tierButtons = new ButtonGroup();
        tierButtons.add(freeTierRadioButton);
        tierButtons.add(hobbyTierRadioButton);
        tierButtons.add(proTierRadioButton);
        tierButtons.add(adminRadioButton);
        tierButtons.setSelected(freeTierRadioButton.getModel(), true);
        SignUpButton.addActionListener(this);
        profilePicButton.addActionListener(this);
        toLoginButton.addActionListener(this);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        passwordLabel = new JLabel();
        passwordLabel.setText("Password:");
        passwordLabel.setVerticalAlignment(3);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = -1.0;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(passwordLabel, gbc);
        nicknameLabel = new JLabel();
        nicknameLabel.setText("Nickname:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(nicknameLabel, gbc);
        nicknameTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(nicknameTextField, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Name:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Surname:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(label2, gbc);
        passwordField = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(passwordField, gbc);
        nameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(nameField, gbc);
        surnameField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(surnameField, gbc);
        SignUpButton = new JButton();
        SignUpButton.setText("signUp");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(SignUpButton, gbc);
        profilePicButton = new JButton();
        profilePicButton.setText("Choose Photo");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(profilePicButton, gbc);
        photoLabel = new JLabel();
        photoLabel.setText("photo");
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 5;
        gbc.gridheight = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(photoLabel, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spacer2, gbc);
        freeTierRadioButton = new JRadioButton();
        freeTierRadioButton.setText("freeTier");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(freeTierRadioButton, gbc);
        adminRadioButton = new JRadioButton();
        adminRadioButton.setText("Admin");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(adminRadioButton, gbc);
        hobbyTierRadioButton = new JRadioButton();
        hobbyTierRadioButton.setText("hobbyTier");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(hobbyTierRadioButton, gbc);
        proTierRadioButton = new JRadioButton();
        proTierRadioButton.setText("ProTier");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        mainPanel.add(proTierRadioButton, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer3, gbc);
        toLoginButton = new JButton();
        toLoginButton.setText("Already Have an Account?Log in");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(toLoginButton, gbc);
        final JPanel spacer4 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.VERTICAL;
        mainPanel.add(spacer4, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton p) {
            if (Objects.equals(((JButton) e.getSource()).getText(), profilePicButton.getText())) {
                System.out.println("Clicked to choose pp");
                ChoosePhotoCommand c = new ChoosePhotoCommand(100, 100);
                ImageIcon icon = c.executeWithReturn();
                photoLabel.setIcon(icon);
            } else if (Objects.equals(((JButton) e.getSource()).getText(), SignUpButton.getText())) {
                String nickname = nicknameTextField.getText();
                String name = nameField.getText();
                String surname = surnameField.getText();
                User.tiers tier;
                if (tierButtons.getSelection() == freeTierRadioButton.getModel()) {
                    tier = User.tiers.FreeTier;
                } else if (tierButtons.getSelection() == hobbyTierRadioButton.getModel()) {
                    tier = User.tiers.HobbyTier;
                } else if (tierButtons.getSelection() == adminRadioButton.getModel()) {
                    tier = User.tiers.Admin;
                } else {
                    tier = User.tiers.ProTier;
                }

                char[] password = passwordField.getPassword();
                if (photoLabel.getIcon() != null) {
                    Image img = ((ImageIcon) photoLabel.getIcon()).getImage();
                    RenderedImage r = ImageSecretary.convertImageToRenderedImage(img);
                    Command c = new SignUpCommand(nickname, name, surname, password, tier, r);
                    c.execute();
                } else {
                    Command c = new SignUpCommand(nickname, name, surname, password, tier);
                    c.execute();
                }


            } else if (((JButton) e.getSource()).getText().equals(toLoginButton.getText())) {
                UIController.getUIController().setCurrentPage(Pages.Login);
            }

        }
    }

    @Override
    public void onStart() {
        clearFields();
    }

    public void clearFields() {
        nicknameTextField.setText("");
        nameField.setText("");
        surnameField.setText("");
        passwordField.setText("");
        photoLabel.setIcon(null);
    }

    @Override
    public JPanel getPanel() {
        return mainPanel;
    }

    @Override
    public boolean isMenuVisible() {
        return false;
    }
}
